import type {
  DayPhase,
  LocationDefinition,
  NpcDefinition,
  PhotoPreset,
  QuestDefinition,
  QuestProgress,
  WorldObject,
} from '../types/game';

export const WORLD_WIDTH = 6200;
export const WORLD_HEIGHT = 960;

export const LOCATIONS: LocationDefinition[] = [
  {
    id: 'house',
    title: 'Старый дом',
    subtitle: 'Кухня, гостиная, веранда, чердак, подвал, кассетная комната и крыша',
    bounds: { x: 0, y: 0, width: 1380, height: WORLD_HEIGHT },
    palette: { sky: 0xf7b98f, ground: 0x6e4c38, accent: 0xffd38a, shadow: 0x2a1b27 },
    atmosphere: ['скрип половиц', 'лампы с янтарным светом', 'кассетный шум', 'дождь по окнам'],
  },
  {
    id: 'yard',
    title: 'Двор с гирляндами',
    subtitle: 'Костёр, гамак, качели, сарай, клумбы, бельевые верёвки и кошачий уголок',
    bounds: { x: 1380, y: 0, width: 1320, height: WORLD_HEIGHT },
    palette: { sky: 0xf5a65d, ground: 0x49633d, accent: 0xffe29a, shadow: 0x1f2d2c },
    atmosphere: ['цикады', 'дым костра', 'ветер в бельевых верёвках', 'мягкие тени травы'],
  },
  {
    id: 'forest',
    title: 'Лесная тропа',
    subtitle: 'Туман, заброшенный колодец, грибы, домик на дереве и ночные духи',
    bounds: { x: 2700, y: 0, width: 1240, height: WORLD_HEIGHT },
    palette: { sky: 0x8fb7a7, ground: 0x314b37, accent: 0x9fe0b1, shadow: 0x11251d },
    atmosphere: ['туман между соснами', 'шорох листьев', 'лесные светлячки', 'далёкие колокольчики'],
  },
  {
    id: 'pond',
    title: 'Пруд',
    subtitle: 'Мостик, лодка, кувшинки, камыши, лягушки и отражение луны',
    bounds: { x: 3940, y: 0, width: 1140, height: WORLD_HEIGHT },
    palette: { sky: 0x9fc7d9, ground: 0x286073, accent: 0xb6e5df, shadow: 0x13283e },
    atmosphere: ['плеск воды', 'лягушки', 'лунные отражения', 'камыши на ветру'],
  },
  {
    id: 'greenhouse',
    title: 'Теплица',
    subtitle: 'Закрытая мистическая оранжерея с магическими растениями и особой музыкой',
    bounds: { x: 5080, y: 0, width: 1120, height: WORLD_HEIGHT },
    lockedBy: 'greenhouseOpen',
    palette: { sky: 0x7e9f9e, ground: 0x315d4a, accent: 0xc4ffbf, shadow: 0x122a24 },
    atmosphere: ['тёплое стекло', 'запах влажной земли', 'магические растения', 'тихие синты'],
  },
];

export const NPCS: NpcDefinition[] = [
  {
    id: 'lekha',
    name: 'Лёха',
    role: 'тихий гитарист',
    appearance: 'блондин с волосами до ушей, oversized кофта, спокойный взгляд',
    personality: 'добрый, тихий, эмоциональный',
    questId: 'old-cassette',
    favoriteGifts: ['cassette-warm-evening', 'guitar-pick'],
    schedule: { morning: 'house', day: 'yard', goldenHour: 'yard', blueEvening: 'house', night: 'house' },
    dialogue: {
      morning: ['Рыжик, слышишь? Дом утром звучит как старая гитара.', 'Я оставил тебе миску у кухни.'],
      day: ['Если найдёшь кассету в сарае, мы снова включим музыку на крыльце.'],
      goldenHour: ['Закат здесь всегда будто помнит тех, кто играл во дворе.'],
      blueEvening: ['Хочешь посидеть рядом? Я сыграю тихо.'],
      night: ['Ночью дом не страшный. Он просто разговаривает.'],
      rain: ['Дождь идеально ложится на перебор. Послушай окно.'],
      storm: ['Если погаснет свет, держись рядом. Вместе теплее.'],
      friend: ['Ты вернул дому голос, Рыжик. Спасибо.'],
    },
  },
  {
    id: 'igor',
    name: 'Игорь',
    role: 'гаражный рокер',
    appearance: 'чёрная куртка, цепочка, эмоциональный взгляд',
    personality: 'громкий снаружи, очень заботливый внутри',
    questId: 'lost-pick',
    favoriteGifts: ['guitar-pick', 'cassette-garage-rain'],
    schedule: { morning: 'yard', day: 'house', goldenHour: 'yard', blueEvening: 'yard', night: 'house' },
    dialogue: {
      morning: ['Рыжик, если видишь мой медиатор, не играй им под шкафом. Хотя ладно, играй.'],
      day: ['Гаражная репетиция будет мягкой. Почти.'],
      goldenHour: ['Смотри, как свет цепляется за струны.'],
      blueEvening: ['Ночью рок тоже может быть уютным.'],
      night: ['Я убавлю усилитель. Честно.'],
      rain: ['Дождь на крыше гаража звучит как драм-машина.'],
      storm: ['Гром? Отличное вступление, но генератор надо включить.'],
      friend: ['Ты не кот, ты наш продюсер с хвостом.'],
    },
  },
  {
    id: 'nastya',
    name: 'Настя',
    role: 'фотограф воспоминаний',
    appearance: 'зелёные глаза, тёплая кофта, плёночная камера',
    personality: 'наблюдательная, бережная, светлая',
    questId: 'firefly-photo',
    favoriteGifts: ['photo-fireflies', 'moon-lily'],
    schedule: { morning: 'yard', day: 'pond', goldenHour: 'pond', blueEvening: 'pond', night: 'pond' },
    dialogue: {
      morning: ['Сегодня мягкий свет. Идеально для альбома дома.'],
      day: ['Камера любит, когда ты прыгаешь через траву.'],
      goldenHour: ['Золото на шерсти — это отдельная магия.'],
      blueEvening: ['Приведи светлячков к пруду, и мы поймаем лето на плёнку.'],
      night: ['Не двигайся. Ты сейчас как маленькое созвездие.'],
      rain: ['Капли на объективе иногда честнее идеальной резкости.'],
      storm: ['Сниму потом. Сейчас лучше найти свечи.'],
      friend: ['Наш альбом пахнет травой, дождём и твоим мурчанием.'],
    },
  },
  {
    id: 'liza',
    name: 'Лиза',
    role: 'хаотичная декораторка',
    appearance: 'розовые волосы, наклейки на рукавах, быстрые жесты',
    personality: 'солнечная, шумная, нежная',
    questId: 'lost-stickers',
    favoriteGifts: ['sticker-sun', 'string-lights'],
    schedule: { morning: 'yard', day: 'yard', goldenHour: 'yard', blueEvening: 'house', night: 'house' },
    dialogue: {
      morning: ['Сегодня двор станет ещё на один процент милее. Минимум.'],
      day: ['Если найдёшь наклейки, я украшу кошачий уголок!'],
      goldenHour: ['Гирлянды должны включаться именно сейчас. Это закон красоты.'],
      blueEvening: ['Вечеринка будет тихая. Ну, почти тихая.'],
      night: ['Я клею звёзды на банки, чтобы они светились.'],
      rain: ['Дождевые вечеринки underrated.'],
      storm: ['Окей, гром не в моей эстетике. Где свечи?'],
      friend: ['Ты официально главный дизайнер лапами.'],
    },
  },
  {
    id: 'mag',
    name: 'Маг',
    role: 'ночной хранитель теплицы',
    appearance: 'тёмный плащ, светлая улыбка, карманный колокольчик',
    personality: 'загадочный, мягко-ироничный, внимательный',
    questId: 'moon-bell',
    favoriteGifts: ['moon-bell', 'strange-note'],
    schedule: { morning: 'forest', day: 'greenhouse', goldenHour: 'forest', blueEvening: 'forest', night: 'greenhouse' },
    dialogue: {
      morning: ['Не каждый кот слышит, как растёт тишина. Ты слышишь.'],
      day: ['Теплица откроется не ключом, а заботой. Хотя ключ тоже понадобится.'],
      goldenHour: ['В этот час тени становятся честнее людей.'],
      blueEvening: ['Иди на звук колокольчика, но не торопи туман.'],
      night: ['Луна запоминает тех, кто идёт мягко.'],
      rain: ['Дождь кормит старые тайны.'],
      storm: ['Гроза проверяет не смелость, а способность остаться рядом.'],
      friend: ['Теперь ты знаешь: магия здесь всегда была бытовой.'],
    },
  },
  {
    id: 'sonya',
    name: 'Соня',
    role: 'путешественница лесных троп',
    appearance: 'спокойные глаза, походный рюкзак, полевые ленты',
    personality: 'тихая, уверенная, любит карты',
    questId: 'forest-path',
    favoriteGifts: ['pine-cone-map', 'forest-ribbon'],
    schedule: { morning: 'forest', day: 'forest', goldenHour: 'pond', blueEvening: 'forest', night: 'house' },
    dialogue: {
      morning: ['Лес утром открывает короткие тропы для тех, кто не шумит.'],
      day: ['Пойдём по мху? Там есть старый колодец.'],
      goldenHour: ['Пруд — лучший компас на закате.'],
      blueEvening: ['Если увидишь свет между деревьями, не бойся. Это не всегда люди.'],
      night: ['Ночью я возвращаюсь в дом. Даже путешественникам нужен чай.'],
      rain: ['После дождя тропа пахнет грибами.'],
      storm: ['В грозу деревья лучше не испытывать.'],
      friend: ['Ты запомнил тропы лапами лучше моей карты.'],
    },
  },
  {
    id: 'nena',
    name: 'Нэна',
    role: 'летописец странностей',
    appearance: 'очки, блокнот, внимательный взгляд',
    personality: 'наблюдательная, суховато-смешная, добрая',
    questId: 'strange-notes',
    favoriteGifts: ['strange-note', 'cassette-archive'],
    schedule: { morning: 'house', day: 'forest', goldenHour: 'house', blueEvening: 'house', night: 'yard' },
    dialogue: {
      morning: ['Запись: кот снова понял больше всех присутствующих.'],
      day: ['В лесу есть повторяющиеся звуки. Слишком повторяющиеся.'],
      goldenHour: ['Свет на пыли в гостиной похож на старую плёнку.'],
      blueEvening: ['Я нашла записи о музыкантах, которые жили здесь до нас.'],
      night: ['Ночные заметки честнее дневных.'],
      rain: ['Чернила плывут, но мысли становятся яснее.'],
      storm: ['Фиксирую: все делают вид, что не боятся. Кроме честного кота.'],
      friend: ['В архиве теперь есть глава про тебя. Главная.'],
    },
  },
  {
    id: 'kristina',
    name: 'Кристина',
    role: 'мастерица двора',
    appearance: 'тёмная одежда, татуировки, набор инструментов',
    personality: 'собранная, заботливая, говорит делом',
    questId: 'broken-lantern',
    favoriteGifts: ['lantern-bulb', 'rusty-key'],
    schedule: { morning: 'yard', day: 'greenhouse', goldenHour: 'yard', blueEvening: 'yard', night: 'house' },
    dialogue: {
      morning: ['Фонарик починим, забор подтянем, кота погладим. План хороший.'],
      day: ['Старые вещи не сломаны. Они ждут правильных рук.'],
      goldenHour: ['Когда гирлянды зажгутся, двор станет похож на сцену.'],
      blueEvening: ['Принеси лампочку, и я сделаю свет мягче.'],
      night: ['Инструменты спят. Люди тоже должны. Коты как хотят.'],
      rain: ['Дождь показывает, где крыша честно протекает.'],
      storm: ['Генератор в гараже. Нужен ключ и спокойные лапы.'],
      friend: ['Ты лучший тестировщик тёплых мест.'],
    },
  },
  {
    id: 'danya',
    name: 'Даня',
    role: 'изобретатель странных игрушек',
    appearance: 'красные очки, провода в карманах, коробка деталей',
    personality: 'рассеянный, добрый, любопытный',
    questId: 'treasure-box',
    favoriteGifts: ['cat-toy-spark', 'old-battery'],
    schedule: { morning: 'house', day: 'yard', goldenHour: 'yard', blueEvening: 'yard', night: 'house' },
    dialogue: {
      morning: ['Я сделал мышь на пружинке. Она почти не пугает людей.'],
      day: ['Коробка сокровищ где-то во дворе. Если она пищит — это нормально.'],
      goldenHour: ['Закат отлично заряжает странные устройства. Наверное.'],
      blueEvening: ['Тебе идёт лежать на клавиатуре. Код стал уютнее.'],
      night: ['Ночью все идеи звучат гениальнее. Это опасно.'],
      rain: ['Электронику под дождь нельзя. Кота можно, если кот согласен.'],
      storm: ['Генератор? Я знаю схему. Где схема?'],
      friend: ['Ты не сломал ни одну игрушку. Ты улучшил их лапой.'],
    },
  },
  {
    id: 'prokhor',
    name: 'Прохор',
    role: 'строитель больших жестов',
    appearance: 'широкие плечи, татуированные руки, спокойная улыбка',
    personality: 'надёжный, молчаливый, очень мягкий с животными',
    favoriteGifts: ['fence-nail', 'warm-tea'],
    schedule: { morning: 'yard', day: 'yard', goldenHour: 'yard', blueEvening: 'house', night: 'house' },
    dialogue: {
      morning: ['Забор сегодня держится лучше. Ты проверял сверху?'],
      day: ['Перенесу старую скамейку к костру. Там ей место.'],
      goldenHour: ['Большие вещи тоже любят мягкий свет.'],
      blueEvening: ['Если захочешь на плечо — прыгай. Поймаю.'],
      night: ['Спокойной ночи, маленький хозяин двора.'],
      rain: ['Мокрые доски тяжёлые, но запах хороший.'],
      storm: ['Двери придержу. Ты ищи свечи.'],
      friend: ['Дом стал крепче, потому что в нём ходишь ты.'],
    },
  },
];

export const QUESTS: QuestDefinition[] = [
  {
    id: 'old-cassette',
    title: 'Старая кассета',
    giver: 'Лёха',
    summary: 'Лёха потерял кассету в сарае. Рыжик пролезает между коробками и возвращает дому музыку.',
    unlocks: 'cassetteFound',
    reward: 'Музыка на крыльце и воспоминание о прежних музыкантах',
    steps: [
      { id: 'talk-lekha', text: 'Поговорить с Лёхой у дома', target: 'lekha' },
      { id: 'move-boxes', text: 'Поиграть с коробками в сарае', target: 'shed-boxes', count: 2 },
      { id: 'find-cassette', text: 'Найти кассету под старым велосипедом', target: 'cassette-warm-evening' },
    ],
  },
  {
    id: 'firefly-photo',
    title: 'Фото со светлячками',
    giver: 'Настя',
    summary: 'Ночная фотография у пруда получится, если Рыжик приведёт к мосткам светлячков.',
    reward: 'Фото в альбом и редкая ночь светлячков',
    steps: [
      { id: 'talk-nastya', text: 'Поговорить с Настей в синий вечер или ночью', target: 'nastya' },
      { id: 'catch-fireflies', text: 'Поймать три светлячка', target: 'firefly', count: 3 },
      { id: 'pose-pond', text: 'Вернуться на мостик у пруда', target: 'pond-photo-spot' },
    ],
  },
  {
    id: 'storm',
    title: 'Гроза',
    giver: 'Кристина',
    summary: 'Во время грозы отключается свет. Нужно найти свечи и запустить генератор в гараже.',
    unlocks: 'stormResolved',
    reward: 'Дом собирает всех вместе, а двор получает стабильное электричество',
    steps: [
      { id: 'find-candles', text: 'Найти свечи на кухне', target: 'kitchen-candles' },
      { id: 'garage-key', text: 'Достать ключ из-под коврика на веранде', target: 'garage-key' },
      { id: 'start-generator', text: 'Включить генератор в гараже', target: 'generator' },
    ],
  },
  {
    id: 'roof-night',
    title: 'Ночь на крыше',
    giver: 'Лиза',
    summary: 'Все хотят смотреть метеоритный дождь. Рыжик готовит пледы, музыку и безопасный путь на крышу.',
    unlocks: 'roofNightPrepared',
    reward: 'Кинематографичная сцена на крыше и новая кассета',
    steps: [
      { id: 'bring-blanket', text: 'Принести плед из спальни', target: 'roof-blanket' },
      { id: 'bring-speaker', text: 'Включить колонки в кассетной комнате', target: 'speakers' },
      { id: 'climb-roof', text: 'Забраться на крышу по виноградной лозе', target: 'roof-vine' },
    ],
  },
  {
    id: 'moon-bell',
    title: 'Колокольчик луны',
    giver: 'Маг',
    summary: 'Маг слышит старый колокольчик в тумане. Рыжик идёт в лес ночью и находит скрытый проход.',
    unlocks: 'moonBellFound',
    reward: 'Лунный колокольчик и подсказка к теплице',
    steps: [
      { id: 'meet-mag', text: 'Встретить Мага после захода солнца', target: 'mag' },
      { id: 'follow-chime', text: 'Пройти через туман к заброшенному колодцу', target: 'old-well' },
      { id: 'take-bell', text: 'Найти колокольчик луны', target: 'moon-bell' },
    ],
  },
  {
    id: 'greenhouse',
    title: 'Теплица',
    giver: 'Кристина и Маг',
    summary: 'Главный сюжетный квест: ключи, электричество и дверь оживляют мистическую теплицу.',
    unlocks: 'greenhouseOpen',
    reward: 'Новая локация, магические растения и особая музыка',
    steps: [
      { id: 'collect-key', text: 'Найти ржавый ключ возле колодца', target: 'rusty-key' },
      { id: 'restore-power', text: 'Починить фонарик и питание двора', target: 'lantern-bulb' },
      { id: 'open-door', text: 'Открыть дверь теплицы ночью', target: 'greenhouse-door' },
    ],
  },
  {
    id: 'lost-pick',
    title: 'Пропавший медиатор',
    giver: 'Игорь',
    summary: 'Игорь потерял медиатор перед мини-концертом. Рыжик ищет его под усилителем и коробками.',
    reward: 'Гаражная репетиция и дружба с Игорем',
    steps: [
      { id: 'talk-igor', text: 'Поговорить с Игорем во дворе', target: 'igor' },
      { id: 'search-amp', text: 'Проверить усилитель', target: 'garage-amp' },
      { id: 'pick-found', text: 'Подобрать медиатор', target: 'guitar-pick' },
    ],
  },
  {
    id: 'lost-stickers',
    title: 'Потерянные наклейки',
    giver: 'Лиза',
    summary: 'Лиза рассыпала наклейки. Когда Рыжик приносит их обратно, двор становится ярче.',
    reward: 'Украшение кошачьего уголка и рост декора',
    steps: [
      { id: 'talk-liza', text: 'Поговорить с Лизой', target: 'liza' },
      { id: 'find-stickers', text: 'Собрать две наклейки возле гамака', target: 'sticker-sun', count: 2 },
    ],
  },
  {
    id: 'forest-path',
    title: 'Лесная тропа',
    giver: 'Соня',
    summary: 'Соня показывает мягкие тропы, которые открывают секреты леса.',
    reward: 'Скрытые зоны леса и сосновая карта',
    steps: [
      { id: 'walk-sonya', text: 'Пройти с Соней к домику на дереве', target: 'sonya' },
      { id: 'map-cone', text: 'Найти сосновую карту', target: 'pine-cone-map' },
    ],
  },
  {
    id: 'strange-notes',
    title: 'Странные записи',
    giver: 'Нэна',
    summary: 'Нэна собирает странности дома и раскрывает лор прежних музыкантов.',
    reward: 'Архивные записи и путь к финалу',
    steps: [
      { id: 'talk-nena', text: 'Поговорить с Нэной в гостиной', target: 'nena' },
      { id: 'collect-notes', text: 'Найти три странные записи', target: 'strange-note', count: 3 },
    ],
  },
  {
    id: 'broken-lantern',
    title: 'Сломанный фонарик',
    giver: 'Кристина',
    summary: 'Фонарик у сарая мерцает. Рыжик приносит лампочку и помогает сделать двор безопаснее.',
    unlocks: 'yardLightsFixed',
    reward: 'Мягкие гирлянды, свет у сарая и новые вечерние события',
    steps: [
      { id: 'talk-kristina', text: 'Поговорить с Кристиной', target: 'kristina' },
      { id: 'find-bulb', text: 'Найти лампочку на чердаке', target: 'lantern-bulb' },
      { id: 'fix-lantern', text: 'Вернуться к фонарику у сарая', target: 'broken-lantern' },
    ],
  },
  {
    id: 'treasure-box',
    title: 'Коробка сокровищ',
    giver: 'Даня',
    summary: 'Даня сделал коробку игрушек, но она спряталась. Кот, конечно, лучше всех знает коробки.',
    reward: 'Игрушка с искрой и мини-игра с коробками',
    steps: [
      { id: 'talk-danya', text: 'Поговорить с Даней', target: 'danya' },
      { id: 'find-box', text: 'Отыскать пищащую коробку', target: 'treasure-box' },
      { id: 'play-toy', text: 'Поиграть с новой игрушкой', target: 'cat-toy-spark' },
    ],
  },
];

export const WORLD_OBJECTS: WorldObject[] = [
  {
    id: 'cassette-warm-evening',
    title: 'Кассета "Тёплый вечер"',
    location: 'yard',
    position: { x: 1860, y: 645 },
    kind: 'cassette',
    description: 'Пыльная кассета из сарая. Пахнет деревом и летним дождём.',
    collectable: true,
    questId: 'old-cassette',
  },
  {
    id: 'cassette-garage-rain',
    title: 'Кассета "Гараж под дождём"',
    location: 'house',
    position: { x: 980, y: 612 },
    kind: 'cassette',
    description: 'Роковая запись с мягким шумом крыши.',
    collectable: true,
    hiddenUntil: { stormResolved: true },
  },
  {
    id: 'cassette-archive',
    title: 'Архивная кассета',
    location: 'house',
    position: { x: 510, y: 462 },
    kind: 'cassette',
    description: 'Старые голоса прежних жителей дома.',
    collectable: true,
  },
  {
    id: 'photo-fireflies',
    title: 'Фото со светлячками',
    location: 'pond',
    position: { x: 4400, y: 610 },
    kind: 'photo',
    description: 'Настя поймала кадр, где Рыжик светится как летнее созвездие.',
    collectable: true,
    hiddenUntil: { cassetteFound: true },
    questId: 'firefly-photo',
  },
  {
    id: 'strange-note-1',
    title: 'Запись Нэны: голоса на чердаке',
    location: 'house',
    position: { x: 720, y: 410 },
    kind: 'note',
    description: 'В заметке говорится, что музыка иногда включалась сама.',
    collectable: true,
  },
  {
    id: 'strange-note-2',
    title: 'Запись Нэны: колодец',
    location: 'forest',
    position: { x: 3350, y: 626 },
    kind: 'note',
    description: 'Слова о колокольчике, который слышен только в тумане.',
    collectable: true,
  },
  {
    id: 'strange-note-3',
    title: 'Запись Нэны: теплица',
    location: 'greenhouse',
    position: { x: 5480, y: 590 },
    kind: 'note',
    description: 'Кто-то выращивал в теплице растения, реагирующие на песни.',
    collectable: true,
    hiddenUntil: { greenhouseOpen: true },
  },
  {
    id: 'moon-bell',
    title: 'Колокольчик луны',
    location: 'forest',
    position: { x: 3580, y: 520 },
    kind: 'memory',
    description: 'Тихо звенит, когда рядом вспоминают хорошее.',
    collectable: true,
    questId: 'moon-bell',
  },
  {
    id: 'rusty-key',
    title: 'Ржавый ключ',
    location: 'forest',
    position: { x: 3300, y: 665 },
    kind: 'tool',
    description: 'Ключ от теплицы, найденный возле колодца.',
    collectable: true,
    hiddenUntil: { moonBellFound: true },
    questId: 'greenhouse',
  },
  {
    id: 'lantern-bulb',
    title: 'Тёплая лампочка',
    location: 'house',
    position: { x: 620, y: 512 },
    kind: 'tool',
    description: 'Лампочка для фонарика у сарая.',
    collectable: true,
    questId: 'broken-lantern',
  },
  {
    id: 'guitar-pick',
    title: 'Медиатор Игоря',
    location: 'yard',
    position: { x: 2260, y: 692 },
    kind: 'quest',
    description: 'Чёрный медиатор с рыжей шерстинкой.',
    collectable: true,
    questId: 'lost-pick',
  },
  {
    id: 'sticker-sun',
    title: 'Солнечная наклейка',
    location: 'yard',
    position: { x: 1655, y: 670 },
    kind: 'decor',
    description: 'Наклейка Лизы для кошачьего уголка.',
    collectable: true,
    questId: 'lost-stickers',
  },
  {
    id: 'sticker-moon',
    title: 'Лунная наклейка',
    location: 'yard',
    position: { x: 1750, y: 710 },
    kind: 'decor',
    description: 'Вторая наклейка Лизы, немного в траве.',
    collectable: true,
    questId: 'lost-stickers',
  },
  {
    id: 'pine-cone-map',
    title: 'Сосновая карта',
    location: 'forest',
    position: { x: 3000, y: 620 },
    kind: 'memory',
    description: 'Шишка с ленточками Сони, отмечающими короткие тропы.',
    collectable: true,
    questId: 'forest-path',
  },
  {
    id: 'treasure-box',
    title: 'Пищащая коробка',
    location: 'yard',
    position: { x: 2020, y: 652 },
    kind: 'toy',
    description: 'Коробка Дани с игрушечной мышью и мягким моторчиком.',
    collectable: true,
    questId: 'treasure-box',
  },
  {
    id: 'cat-toy-spark',
    title: 'Игрушка с искрой',
    location: 'yard',
    position: { x: 2150, y: 690 },
    kind: 'toy',
    description: 'Маленькая безопасная искра, за которой Рыжик гоняется кругами.',
    collectable: true,
    hiddenUntil: { yardLightsFixed: true },
  },
  {
    id: 'moon-lily',
    title: 'Лунная кувшинка',
    location: 'pond',
    position: { x: 4700, y: 680 },
    kind: 'plant',
    description: 'Редкий цветок, отражающий звёзды даже днём.',
    collectable: true,
  },
  {
    id: 'old-battery',
    title: 'Старая батарейка',
    location: 'house',
    position: { x: 820, y: 690 },
    kind: 'tool',
    description: 'Даня уверяет, что она "почти волшебная".',
    collectable: true,
  },
  {
    id: 'fence-nail',
    title: 'Большой гвоздь',
    location: 'yard',
    position: { x: 2510, y: 710 },
    kind: 'tool',
    description: 'Прохор починит забор, если Рыжик не укатит гвоздь первым.',
    collectable: true,
  },
  {
    id: 'firefly-cluster',
    title: 'Рой светлячков',
    location: 'pond',
    position: { x: 4300, y: 540 },
    kind: 'firefly',
    description: 'Летние огоньки, которые следуют за мягким мурчанием.',
    collectable: false,
    questId: 'firefly-photo',
  },
];

export const PHOTO_PRESETS: PhotoPreset[] = [
  { id: 'warm-film', title: 'Тёплая плёнка', blur: 1, grain: 0.28, saturation: 1.12, vignette: 0.35 },
  { id: 'rain-window', title: 'Дождь на окне', blur: 2.2, grain: 0.18, saturation: 0.86, vignette: 0.46 },
  { id: 'lofi-night', title: 'Lo-fi ночь', blur: 1.4, grain: 0.32, saturation: 0.96, vignette: 0.58 },
  { id: 'ghibli-sunset', title: 'Закатная акварель', blur: 0.6, grain: 0.12, saturation: 1.25, vignette: 0.22 },
];

export const createInitialQuestProgress = (): Record<string, QuestProgress> =>
  Object.fromEntries(
    QUESTS.map((quest, index) => [
      quest.id,
      {
        status: index < 4 ? 'available' : 'locked',
        stepIndex: 0,
        counters: {},
      },
    ]),
  );

export const phaseFromMinute = (minute: number): DayPhase => {
  const normalized = ((minute % 1440) + 1440) % 1440;
  if (normalized >= 300 && normalized < 660) return 'morning';
  if (normalized >= 660 && normalized < 1020) return 'day';
  if (normalized >= 1020 && normalized < 1170) return 'goldenHour';
  if (normalized >= 1170 && normalized < 1260) return 'blueEvening';
  return 'night';
};

export const formatClock = (minute: number) => {
  const normalized = ((Math.floor(minute) % 1440) + 1440) % 1440;
  const hours = Math.floor(normalized / 60)
    .toString()
    .padStart(2, '0');
  const minutes = (normalized % 60).toString().padStart(2, '0');
  return `${hours}:${minutes}`;
};
